### ISSUE TITLE
Add Collabo Discord community server link to main docs sidebar

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/docs#19]
#### Suggested improvement
The link to our Discord community server only exists or can only be accessed from the front page of our community documentation. We need it to also be on the sidebar too in these 3 places so that it is accessible from any where:
- [The community documentation (main page)](https://code-collabo.gitbook.io/docs/collabo-docs-home/readme)
- [The user doc (main page)](https://code-collabo.gitbook.io/users/collabo-user-docs/readme)
- [The contributor doc (main page)](https://code-collabo.gitbook.io/collabo-contributor/collabo-contributor-docs/readme)

#### Additional context
This is our new documentation.

#### Testing checklist
Note: Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] The discord community server link now exists in the new documentation's sidebar for these 3 places in the documentation: The community doc main page, user doc main page and contributor doc main page.
- [ ] I certify that I ran my checklist

**Comment by KamiNation** [comment]
@Ifycode. Good morning assign this to me.
