### ISSUE TITLE
No content in readme

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/docs#35]
Here's the link to our documentation. You will find the link to our discord community server in there incase you need to ask any questions: https://code-collabo.gitbook.io/docs/collabo-docs-home/readme
#

#### Issue description
There is no descriptive content in the Collabo Web App repo: https://github.com/code-collabo/collabo-web-app

#### Additional context
Take a clue from the following repos to add a simplified readme content for the Collabo Web App repo:
- https://github.com/code-collabo/node-mongo-scripts
- https://github.com/code-collabo/docs

#### Testing checklist
Note: Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] Simplified readme content added for Collabo Web App repo, following the footsteps of the example repos.
- [ ] I certify that I ran my checklist

**Comment by aybeedee** [comment]
Hi @Ifycode, I'd like to work on this. Can I kindly be assigned?

**Comment by Ifycode** [comment]
Yes, assigned to you. Please go ahead 👍🏼

**Comment by aybeedee** [comment]
@Ifycode I've put in a pull request. If any changes, additions or deletions are still needed, kindly let me know.
