### ISSUE TITLE
Repo name has changed, fix readme accordingly

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/docs#40]
Repo name for this project has changed https://github.com/code-collabo/collabo-community-app, this has not yet reflected in the repo's readme yet.

Fix the readme accordingly.

**Comment by Dkingofcode** [comment]
Can i work on this issue?

**Comment by Ifycode** [comment]
Assigned to you @Dkingofcode 👍🏼

**Comment by Dkingofcode** [comment]
Thank you very much @Ifycode , pls i have a question, should i create the pull request in the docs folder or the community-collabo-app folder.

**Comment by Ifycode** [comment]
The Readmes of any of our repos are considered as part of docs - since they give instructions. You can't be updating or sending PR to docs repo when the issue says it's for community-app repo. Just follow what's in the issue and you'll be fine. Let me know if you have any questions @Dkingofcode
