### ISSUE TITLE
Move git-and-github course contributing doc content to git-and-github-for-collaboration repo's doc folder

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/docs#5]
- [ ] Move git-and-github course contributing doc content to git-and-github-for-collaboration repo's doc folder
- [ ] Update content

**Comment by oyenuga17** [comment]
I am interested

**Comment by Ifycode** [comment]
Ok assigned to you @oyenuga17 
Is this issue explanatory enough? Or you will need further clarification.

**Comment by oyenuga17** [comment]
@Ifycode  please review at https://github.com/code-collabo/git-and-github-for-collaboration/pull/6
