### ISSUE TITLE
Docs repo needs PR and Issue templates

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/docs#6]
Docs repo needs PR and Issue templates (except for the "report a bug" template).
[Take a clue from the node-mongo's .github folder](https://github.com/code-collabo/node-mongo/tree/develop/.github)

#### Video
https://app.claap.io/code-collabo/docs-issue-1-docs-repo-has-no-pr-or-issue-template-c-k_zUmfU3ae-L9Ecw-v0cPdh

**Comment by oyenuga17** [comment]
@Ifycode  please assign me

**Comment by Ifycode** [comment]
Not yet @oyenuga17 I left a review in your other task PR.

**Comment by oyenuga17** [comment]
@oyenuga17  can i go ahead with this now ?

**Comment by Ifycode** [comment]
Not yet @oyenuga17 I left a review in your other task PR.

**Comment by Ifycode** [comment]
Do you still wish to take up this issue? @oyenuga17

**Comment by oyenuga17** [comment]
> Do you still wish to take up this issue? @oyenuga17

oh, yes i will see to it

**Comment by Ifycode** [comment]
Ok. Assigned to you then @oyenuga17 🤝
